### ISSUE TITLE
Sorting by Last action does not work

### ISSUE THREAD

**Issue by brita-sed** [InteractiveFaultLocalization/iFL4Eclipse#157]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores... button. 
1. At iFL Filters window click Add rule button. 
1. Add Sort rule by Last action. 

**Expected results**
* Widgets will sort by Last action. 

**Received results**
* Ordering by Last action does not work. 

![sort_rule_last_action](https://user-images.githubusercontent.com/16755484/86227640-9dc5f300-bb8d-11ea-8785-7ecc17beeb7d.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.144.4
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
This bug is still alive. Tested version: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting.2

![last_action_rendezes_wrong_02](https://user-images.githubusercontent.com/16755484/112313024-b50eb880-8ca7-11eb-9968-d2d537771e16.jpg)
![last_action_rendezes_wrong_01](https://user-images.githubusercontent.com/16755484/112313027-b63fe580-8ca7-11eb-80e2-75d0697d9a93.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V2.general_fixes.2

**Comment by brita-sed** [comment]
This bug has been corrected. 

![last_action_corrected](https://user-images.githubusercontent.com/16755484/116073751-210e8300-a691-11eb-914c-12e2e1db1f15.jpg)
