### ISSUE TITLE
Unhandled event loop exception by clicking on iFL button

### ISSUE THREAD

**Issue by brita-sed** [InteractiveFaultLocalization/iFL4Eclipse#173]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 

**Expected results**
* The iFL tab will open with the appropriate content. 

**Received results**
* Error message: 
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: javafx/beans/property/StringProperty
* Log file: 
[load_score_log.txt](https://github.com/sed-szeged/iFL4Eclipse/files/5931724/load_score_log.txt)
* I used an older workspace, and the Testproject: 
[TestProject.zip](https://github.com/sed-szeged/iFL4Eclipse/files/5931731/TestProject.zip)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
Installing https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html instead of jdk-version 11 solved the problem. 
Installing e(fx)clipse probably also needed (Eclipse > Help > Install new software...)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting.2

**Comment by Dhorvath1294** [comment]
e(fx)clipse is no longer needed.

**Comment by brita-sed** [comment]
The bug has been corrected: the iFL plugin has been loaded without any error, no e(fx)clipse was needed. 

![no_efxclipse_needed](https://user-images.githubusercontent.com/16755484/112309216-5f381180-8ca3-11eb-9447-8ee7e638a2b0.jpg)
