### ISSUE TITLE
After selected a faulty element, then start an iFL session again without loading scores, I can use Sorting and Filters tab

### ISSUE THREAD

**Issue by brita-sed** [InteractiveFaultLocalization/iFL4Eclipse#191]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Click Show filters or Show ordering list button without loading a score -> "Load some definded scores to enable filtering /ordering" message appears.
1. Load scores. 
1. Select a faulty element (right click > Selected item seems faulty). 
1. Type its name, then click OK. 
1. Repeat steps 1-3. 

**Expected results**
* As there aren't any scores loaded, there should be a message with "Load some definded scores to enable filtering /ordering" text. 

**Received results**
* After selected a faulty element, then start an iFL session again without loading scores, I can use Sorting and Filters tab. 

![no_load_score_good](https://user-images.githubusercontent.com/16755484/112326344-babecb00-8cb4-11eb-8927-96b99a4a3e24.jpg)
![no_load_score_bad](https://user-images.githubusercontent.com/16755484/112326342-b98d9e00-8cb4-11eb-8ab5-0ab91be4cafc.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting.2
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V2.duallist-sorting.3

**Comment by brita-sed** [comment]
The bug has been corrected.
