### ISSUE TITLE
Navigate to context on element which has more then 0 context: nothing happened

### ISSUE THREAD

**Issue by brita-sed** [InteractiveFaultLocalization/iFL4Eclipse#192]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Load scores. 
1. Select an element, which context size is bigger than 0. 
1. Right click > Navigate to context.

**Expected results**
* Eclipse will open the context files in the editor. 

**Received results**
* Nothing happened. OR
* The Parent type class will open in the editor. 
* If "Navigate to context" means coloring the context elemets, the menupoint should be "Select the context" or something like this. 

![navigate_to_context](https://user-images.githubusercontent.com/16755484/114050439-8f2f0980-988c-11eb-94fb-e4ea05e047ee.jpg)

**Related issue:**
* #132 If there is no context, "Navigate to context" local menupoint should be disabled

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting.3
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by geryxyz** [comment]
The expected result are correct.

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V2.general_fixes

**Comment by brita-sed** [comment]
The bug has been corrected: choosing "Navigate to context" on every tested element makes iFL open the related files in the editor.
