### ISSUE TITLE
Typo in terminal choice popup

### ISSUE THREAD

**Issue by brita-sed** [InteractiveFaultLocalization/iFL4Eclipse#194]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Load scores. 
1. Select an element. 
1. Right click > Selected item seems faulty (terminal choice)
1. Examine the popup window. 

**Expected results**
* An error message will occur with the right content. 

**Received results**
* There is a typo in the message: a space is missing after the "confirmation" word in the header. 

![typo_in_terminal_choice](https://user-images.githubusercontent.com/16755484/114150715-a584a600-991c-11eb-9bf4-8ddc56cbfc16.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting.3
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V2.general_fixes

**Comment by brita-sed** [comment]
This bug has been corrected. 

![typo_corrected](https://user-images.githubusercontent.com/16755484/115043975-566ae200-9ed5-11eb-8698-a92572dbe22d.jpg)
