### ISSUE TITLE
Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench", org.eclipse.swt.SWTException: Widget is disposed

### ISSUE THREAD

**Issue by brita-sed** [InteractiveFaultLocalization/iFL4Eclipse#195]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Delete eclipse. 
1. Reinstall eclipse. 
1. Start eclipse with the usually used workspace. 
1. Press iFL button. 
1. Close eclipse.  

**Expected results**
* After reinstall eclipse, iFL should be work properly. 

**Received results**
```
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
```
* Log file: 
[exit_error_log.txt](https://github.com/InteractiveFaultLocalization/iFL4Eclipse/files/6286179/exit_error_log.txt)

**Related issue:**
* #115 After reinstall and start eclipse, plenty of error occurs in log: java.lang.RuntimeException and org.eclipse.swt.SWTException

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting.3
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V2.general_fixes.2

**Comment by brita-sed** [comment]
This problem has been solved, there is no error message while closing Eclipse. .
