### ISSUE TITLE
Unhandled event loop exception, UnsupportedOperationException applying a rule with undefined scored elements

### ISSUE THREAD

**Issue by brita-sed** [InteractiveFaultLocalization/iFL4Eclipse#200]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. In the generated csv file delete some rows. 
1. Load scores -> load this modified csv. 
1. Click Hide undefined button to show undefined scored elements. 
1. Click "Show filters" button. 
1. Click "Add rule" button. 
1. Add a score rule, e.g. Score <= 1. 

**Expected results**
* Those elements which have score smaller or equal than 1 will appear. 

**Received results**
* !MESSAGE Unhandled event loop exception
!STACK 0
java.lang.UnsupportedOperationException
* Log file:  [unhandled_loop_exception.txt](https://github.com/InteractiveFaultLocalization/iFL4Eclipse/files/6337286/unhandled_loop_exception.txt)

![unhandled_loop_undefined](https://user-images.githubusercontent.com/16755484/115263729-f1fa8d80-a135-11eb-85fb-e40aa15a03ba.jpg)

**Environment:**
* Package: https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V2.general_fixes
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
The problem is the same when I use Context based feedback with an undefined selected element.

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V2.general_fixes.2

The score filter now always shows undefined elements despite of the filter value.
Context based feedback is now not allowed if undefined elements are in the selection.

**Comment by brita-sed** [comment]
The bug has been corrected, I didn't get any error message.

**Comment by Dhorvath1294** [comment]
The origin of the problem is the same as in issue #210 , so this release should also fix this one:
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V3.0.210.1

**Comment by brita-sed** [comment]
Using rules is corrected: 

![undefined_all_elements](https://user-images.githubusercontent.com/16755484/118245693-68727d00-b4a1-11eb-97ff-5ca7efeb5c4f.jpg)

Context based feedback is also corrected in case of undefined elements: 
![undefined_context_corrected](https://user-images.githubusercontent.com/16755484/118248018-21d25200-b4a4-11eb-8237-9d3d411422d0.jpg)
