### ISSUE TITLE
Unhandled event loop exception, regex.PatternSyntaxException using valid regular expression

### ISSUE THREAD

**Issue by brita-sed** [InteractiveFaultLocalization/iFL4Eclipse#203]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Load scores. 
1. Click Show filters button. 
1. Click Add rule button. 
1. Add a Name rule like this: 
- Enter string: create???????
- Containment: contains
- Matching: partial
- Case-sensitive: no
- Regular expression: yes

**Expected results**
* There will be results to this expression like "createProgram" elements. 

**Received results**
* Results in: - 
* Error in log: [regex_exception_log.txt](https://github.com/InteractiveFaultLocalization/iFL4Eclipse/files/6377033/regex_exception_log.txt)

```
!MESSAGE Unhandled event loop exception
!STACK 0
java.util.regex.PatternSyntaxException: Dangling meta character '?' near index 8
create???????
        ^
	at java.util.regex.Pattern.error(Unknown Source)
	at java.util.regex.Pattern.sequence(Unknown Source)
	at java.util.regex.Pattern.expr(Unknown Source)
```

![regular_exp_02](https://user-images.githubusercontent.com/16755484/116083311-c549f700-a69c-11eb-961b-4cae1e287326.jpg)

**Related issue:**
* #185 After loading scores, added rules should have values, but "-" remained

**Environment:**
* Package: https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V2.general_fixes.2
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
The "create??????" is an invalid expression, but an error message would be better than an exception.

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V3.2.203.1

**Comment by brita-sed** [comment]
An error popup appeared, and there wasn't any error in log, so the bug has been corrected. 

![invalid_expression](https://user-images.githubusercontent.com/16755484/118272735-573a6800-b4c3-11eb-8dd7-3c85fbd6741c.jpg)
