### ISSUE TITLE
Begins (^), ends ($) and * regular expressions doesn't work

### ISSUE THREAD

**Issue by brita-sed** [InteractiveFaultLocalization/iFL4Eclipse#204]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Load scores. 
1. Click Show filters button. 
1. Click Add rule button. 
1. Add a Name rule like this: 
- Enter string: ^update / Matrix$
- Containment: contains
- Matching: partial
- Case-sensitive: no
- Regular expression: yes

**Expected results**
* There will be results to these expression which is
** starts with "update"
** ends with "Matrix"

**Received results**
* There was no results of these regular expressions, but there should be. 

![regular_exp_04](https://user-images.githubusercontent.com/16755484/116095130-69856b00-a6a8-11eb-9b33-2c8cd1fe9dbd.jpg)
![regular_exp_03](https://user-images.githubusercontent.com/16755484/116095135-6ab69800-a6a8-11eb-83ee-cd6b0850739b.jpg)

**Environment:**
* Package: https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V2.general_fixes.2
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
![regular_exp_05](https://user-images.githubusercontent.com/16755484/116103191-a7d25880-a6af-11eb-9d62-42e79e773231.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V2.5.204.1

**Comment by brita-sed** [comment]
The issue works fine with the new Negate Rule function too, so this bug has been corrected.
